 Exercice 1 : Création et manipulation de tableaux

In [1]:
import numpy as np

# Création du tableau de 0 à 9
tableau = np.arange(10)

print(tableau)


[0 1 2 3 4 5 6 7 8 9]


Exercice 2 : Conversion de type et opérations sur les tableaux


In [2]:
import numpy as np

# Conversion de la liste en tableau NumPy et changement de type
tableau_entier = np.array([3.14, 2.17, 0, 1, 2]).astype(int)

print(tableau_entier)


[3 2 0 1 2]


Exercice 3 : Travailler avec des tableaux multidimensionnels


In [3]:
import numpy as np

# Création du tableau 3x3 de 1 à 9
matrice_3x3 = np.arange(1, 10).reshape(3, 3)

print(matrice_3x3)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


Exercice 4 : Création d'un tableau multidimensionnel avec des nombres aléatoires


In [4]:
import numpy as np

# Création du tableau 2D de forme (4, 5) avec des valeurs aléatoires
tableau_aleatoire = np.random.rand(4, 5)

print(tableau_aleatoire)


[[0.85477744 0.79374597 0.04740416 0.40530241 0.56059667]
 [0.72768994 0.00756104 0.23954885 0.24433884 0.80149264]
 [0.13958337 0.41409411 0.89040988 0.38516955 0.62483963]
 [0.20560795 0.05262722 0.85106195 0.53879175 0.75853544]]


Exercice 5 : Indexation des tableaux

In [5]:
import numpy as np

# Tableau 2D d'exemple
tableau_2d = np.array([[10, 20, 30],
                       [40, 50, 60],
                       [70, 80, 90]])

# Sélection de la deuxième ligne (index 1)
deuxieme_ligne = tableau_2d[1]

print(deuxieme_ligne)


[40 50 60]


Exercice 6 : Inversion des éléments


In [6]:
import numpy as np

# Tableau 1D d'exemple
tableau = np.array([10, 20, 30, 40, 50])

# Inversion de l'ordre des éléments
tableau_inverse = tableau[::-1]

print(tableau_inverse)


[50 40 30 20 10]


Exercice 7 : Matrice identité

In [7]:
import numpy as np

# Création d'une matrice identité 4x4
matrice_identite = np.eye(4)

print(matrice_identite)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Exercice 8 : Fonctions agrégées simples

In [8]:
import numpy as np

# Tableau 1D d'exemple contenant les nombres de 0 à 9
tableau = np.arange(10)

# Calcul de la somme et de la moyenne
somme = tableau.sum()
moyenne = tableau.mean()

print(f"Sum: {somme}, Average: {moyenne}")


Sum: 45, Average: 4.5


Exercice 9 : Créer un tableau et modifier sa structure

In [9]:
import numpy as np

# Création du tableau de 1 à 20 et remodelage en 4x5
matrice = np.arange(1, 21).reshape(4, 5)

print(repr(matrice))


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])


Exercice 10 : Sélection conditionnelle des valeurs


In [10]:
import numpy as np

# Tableau d'exemple de 0 à 9
tableau = np.arange(10)

# Extraction des nombres impairs
impairs = tableau[tableau % 2 != 0]

print(repr(impairs))


array([1, 3, 5, 7, 9])
